black:
  max:
  - 89
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 228
  - 125
  - 122
  min:
  - 27
  - 98
  - 86
green:
  max:
  - 255
  - 110
  - 255
  min:
  - 47
  - 0
  - 135
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 12
  - 136
  - 151
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
